# Generated by Django 5.1.3 on 2024-12-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0003_customuser_access_level_customuser_assigned_banca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, to='authenticacion.badge'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skill',
            field=models.ManyToManyField(blank=True, to='authenticacion.skill'),
        ),
    ]
