# Generated by Django 5.1.3 on 2024-12-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0004_badge_skill_customuser_badges_customuser_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='linkedin_profile',
            new_name='linkedinProfile',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
