# Generated by Django 5.1.3 on 2024-12-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedinProfile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
