# Generated by Django 5.1.3 on 2024-12-12 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0007_remove_customuser_biography_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profilePicture',
        ),
    ]
