# Generated by Django 5.1.3 on 2024-12-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0011_customuser_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
