# Generated by Django 5.1.3 on 2024-12-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0013_passwordhistory_totpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totpcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
        migrations.DeleteModel(
            name='TOTPCode',
        ),
    ]
