# Generated by Django 5.1.3 on 2024-12-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0002_bancas_codigo_bancas_mensaje_cancelacion_jugada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancas',
            name='daily_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bancas',
            name='monthly_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bancas',
            name='status',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=10),
        ),
    ]
