# Generated by Django 5.1.4 on 2024-12-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0004_remove_bancas_daily_revenue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisiones', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descontar', models.BooleanField(default=False)),
                ('descontar_de', models.CharField(choices=[('premios', 'Premios'), ('ganancias', 'Ganancias')], default='premios', max_length=10)),
                ('imprimir_ticket', models.BooleanField(default=True)),
                ('imprimir_desglose', models.BooleanField(default=True)),
                ('imprimir_codigo_qr', models.BooleanField(default=True)),
                ('imprimir_nombre_banca', models.BooleanField(default=True)),
                ('imprimir_fecha', models.BooleanField(default=True)),
                ('imprimir_hora', models.BooleanField(default=True)),
                ('imprimir_ubicacion', models.BooleanField(default=True)),
                ('imprimir_telefono', models.BooleanField(default=True)),
                ('banca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bancas.bancas')),
            ],
        ),
    ]
